name: "CI"
on:
  push:
    branches-ignore:
      - "production"
      - "docs"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - ".gitignore"
      - "docs/**"
      - "README.md"
      - "LICENSE"
  pull_request:
    paths:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["3.0", "3.1", "3.2"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: Setup Ruby using ruby-build
        run: |
          curl -fsSL https://github.com/rbenv/ruby-build/archive/master.tar.gz | tar -xz -C /tmp
          /tmp/ruby-build-master/bin/ruby-build ${{ matrix.ruby }} /opt/hostedtoolcache/Ruby/${{ matrix.ruby }}/x64
          touch /opt/hostedtoolcache/Ruby/${{ matrix.ruby }}/x64.complete

      - name: Set up Ruby
        run: echo "/opt/hostedtoolcache/Ruby/${{ matrix.ruby }}/x64/bin" >> $GITHUB_PATH

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: bundle install

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Build Assets
        run: npm i && npm run build

      - name: Test Site
        run: bash tools/test
